version: "3.9"

networks:
  datapipeline:

services:
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - datapipeline

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - datapipeline

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - datapipeline

  spark-master:
    image: apache/spark:3.5.3-scala2.12-java11-python3-ubuntu
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      SPARK_NO_DAEMONIZE: "true"
      IVY_HOME: /tmp/.ivy2
      SPARK_LOCAL_DIRS: /tmp/spark-temp
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - datapipeline
    volumes:
      - ./spark-jobs:/opt/spark-jobs
      - ./data:/data
      - spark_ivy_cache:/tmp/.ivy2

  spark-worker:
    image: apache/spark:3.5.3-scala2.12-java11-python3-ubuntu
    container_name: spark-worker
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_NO_DAEMONIZE: "true"
      IVY_HOME: /tmp/.ivy2
      SPARK_LOCAL_DIRS: /tmp/spark-temp
    networks:
      - datapipeline
    volumes:
      - ./spark-jobs:/opt/spark-jobs
      - ./data:/data
      - spark_ivy_cache:/tmp/.ivy2

  postgres:
    image: arm64v8/postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - datapipeline
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - datapipeline
    depends_on:
      - postgres

  airflow:
    image: apache/airflow:slim-latest-python3.12
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__FERNET_KEY: "test_key_123"
      AIRFLOW__WEBSERVER__SECRET_KEY: "test_key_123"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"  # Don't load example DAGs
    command: >
      bash -c "
      pip install kafka-python psycopg2-binary &&
      airflow db migrate &&
      airflow standalone
      "
    ports:
      - "8082:8080"
    volumes:
    - ./dags:/opt/airflow/dags
    - ./producer:/opt/airflow/producer      
    - ./consumer:/opt/airflow/consumer      
    - ./requirements.txt:/opt/airflow/requirements.txt  
    - /var/run/docker.sock:/var/run/docker.sock  
    networks:
    - datapipeline
    depends_on:
    - postgres

volumes:
  postgres_data:
  spark_ivy_cache: